import { Plugin, MarkdownPostProcessorContext } from 'obsidian';
import { parseWorkout } from './parser';
import { serializeWorkout, updateParamValue, updateSetParamValue, updateExerciseState, updateSetState, addSet, addRest, setRecordedDuration, setSetRecordedDuration, setSetRecordedRest, lockAllFields, createSampleWorkout } from './serializer';
import { renderWorkout } from './renderer';
import { TimerManager } from './timer/manager';
import { FileUpdater } from './file/updater';
import { ParsedWorkout, WorkoutCallbacks, SectionInfo, Exercise } from './types';
import { formatDurationHuman, parseDurationToSeconds } from './parser/exercise';

export default class WorkoutLogPlugin extends Plugin {
	private timerManager: TimerManager = new TimerManager();
	private fileUpdater: FileUpdater | null = null;

	/**
	 * Called when the plugin loads. Initializes the file updater and registers the workout code block processor.
	 * After this, Obsidian will call our processor whenever it encounters a ```workout code block.
	 */
	async onload(): Promise<void> {
		this.fileUpdater = new FileUpdater(this.app);

		// Register the markdown code block processor for 'workout' blocks
		// Tells Obsidian: "When you find a code block of type 'workout', call processWorkoutBlock"
		this.registerMarkdownCodeBlockProcessor('workout', (source, el, ctx) => {
			this.processWorkoutBlock(source, el, ctx);
		});
	}

	/**
	 * Called when the plugin unloads. Cleans up resources, especially the timer manager.
	 * Ensures all active timers are stopped and cleaned up gracefully.
	 */
	onunload(): void {
		this.timerManager.destroy();
	}

	/**
	 * Processes a single workout code block when Obsidian renders it.
	 * This is the main entry point for each workout workout visible on screen.
	 * 
	 * Key responsibilities:
	 * 1. Parse the markdown source into structured workout data
	 * 2. Generate unique ID for this workout (file path + line number)
	 * 3. Sync timer state with file state (handles undo/external edits)
	 * 4. Create callbacks for user interactions
	 * 5. Render the UI and connect timers
	 * 
	 * @param source - Raw markdown text from the code block
	 * @param containerElement - DOM element where UI should be rendered
	 * @param ctx - Obsidian context (has file path, section info, etc)
	 */
	private processWorkoutBlock(
		source: string,
		containerElement: HTMLElement,
		ctx: MarkdownPostProcessorContext
	): void {
		// Parse markdown source into ParsedWorkout structure
		const parsed = parseWorkout(source);
		const sectionInfo = ctx.getSectionInfo(containerElement) as SectionInfo | null;

		// Warn if sectionInfo is null - this can cause issues with multiple workouts
		if (!sectionInfo) {
			console.warn('Workout Log: sectionInfo is null for', ctx.sourcePath, '- file updates may not work correctly');
		}

		// Detect if the parser had to auto-generate sets for legacy/shorthand exercises
		// Auto-generated sets inherit the exact lineIndex of their parent exercise
		const hasAutoGeneratedSets = parsed.exercises.some(
			ex => ex.sets.length > 0 && ex.sets[0]?.lineIndex === ex.lineIndex
		);

		if (hasAutoGeneratedSets && sectionInfo) {
			// Schedule an update to explicitly write the sets back to the file
			setTimeout(() => {
				this.updateFileWithParsed(ctx, sectionInfo, parsed).catch(console.error);
			}, 100);
		}

		// Generate unique workout ID: prevents timer confusion when multiple workouts exist in same file
		// Format: "path/to/file.md:123" where 123 is the line number of workout block start
		const workoutId = `${ctx.sourcePath}:${sectionInfo?.lineStart ?? 0}`;

		// Sync timer state with file state (critical for handling undo/external changes)
		// If user hit undo, file may have changed but timer is still running
		const isTimerRunning = this.timerManager.isTimerRunning(workoutId);
		if (isTimerRunning && parsed.metadata.state !== 'started') {
			// File was reverted to non-started state (user hit undo), stop the timer
			this.timerManager.stopWorkoutTimer(workoutId);
		} else if (isTimerRunning && parsed.metadata.state === 'started') {
			// Timer is running and file is still started. Check if active exercise changed due to undo
			const parsedActiveIndex = parsed.exercises.findIndex(e => e.state === 'inProgress');
			const timerActiveIndex = this.timerManager.getActiveExerciseIndex(workoutId);
			if (parsedActiveIndex >= 0 && parsedActiveIndex !== timerActiveIndex) {
				// Active exercise changed externally (user hit undo on exercise action), resync timer
				this.timerManager.setActiveExerciseIndex(workoutId, parsedActiveIndex);
			}
		} else if (!isTimerRunning && parsed.metadata.state === 'started') {
			// Timer was destroyed (e.g., Obsidian restart or 5-minute timeout), but workout is started.
			// Auto-resume the timer so the user can continue without losing their progress.
			const parsedActiveIndex = parsed.exercises.findIndex(e => e.state === 'inProgress');
			const activeIndex = Math.max(0, parsedActiveIndex);
			
			// Calculate total elapsed time from completed exercises and sets
			let elapsedWorkoutSeconds = 0;
			for (const ex of parsed.exercises) {
				if (ex.state === 'completed') {
					if (ex.recordedTime) elapsedWorkoutSeconds += parseDurationToSeconds(ex.recordedTime);
					if (ex.recordedRest) elapsedWorkoutSeconds += parseDurationToSeconds(ex.recordedRest);
				} else if (ex.state === 'inProgress') {
					for (const set of ex.sets) {
						if (set.state === 'completed') {
							if (set.recordedTime) elapsedWorkoutSeconds += parseDurationToSeconds(set.recordedTime);
							if (set.recordedRest) elapsedWorkoutSeconds += parseDurationToSeconds(set.recordedRest);
						}
					}
				}
			}

			// Recreate the timer at the correct exercise, restoring the total workout time
			this.timerManager.startWorkoutTimer(workoutId, activeIndex, elapsedWorkoutSeconds);

			// Sync to the correct active set within the exercise
			const activeExercise = parsed.exercises[activeIndex];
			if (activeExercise && activeExercise.sets.length > 0) {
				let parsedSetIndex = activeExercise.sets.findIndex(s => s.state === 'inProgress');
				
				if (parsedSetIndex === -1) {
					// If no set is inProgress (e.g., app closed during a rest period), find the first pending set
					parsedSetIndex = activeExercise.sets.findIndex(s => s.state === 'pending');
				}
				
				if (parsedSetIndex === -1) {
					// If all sets are completed but exercise is inProgress (closed during final rest)
					parsedSetIndex = activeExercise.sets.length - 1;
				}
				
				if (parsedSetIndex > 0) {
					this.timerManager.advanceSet(workoutId, activeIndex, parsedSetIndex);
				}
			}
		}

		// Create the callback functions that will handle user interactions
		const callbacks = this.createCallbacks(ctx, sectionInfo, parsed, workoutId);

		// Render the UI and wire up the timers and callbacks
		renderWorkout({
			containerElement,
			parsed,
			callbacks,
			workoutId,
			timerManager: this.timerManager
		});
	}

	// ==================== HELPER METHODS ====================
	/**
	 * Finds the next pending exercise after the given index.
	 * Used to determine which exercise to activate when current one finishes.
	 * @param afterIndex - Start searching after this exercise index
	 * @param exercises - Array of exercises to search
	 * @returns Index of next pending exercise, or -1 if none found
	 */
	private findNextPendingExercise(afterIndex: number, exercises: Exercise[]): number {
		return exercises.findIndex((e, i) => i > afterIndex && e.state === 'pending');
	}

	/**
	 * Serializes the current parsed workout state and saves it back to the file.
	 * This is the main persistence mechanism - all state changes flow through here.
	 * Also handles optional saving to Obsidian properties (front matter) if enabled.
	 * @param ctx - Markdown processor context with file info
	 * @param sectionInfo - Section location in file (for updating the correct code block)
	 * @param parsed - Current workout state to persist
	 */
	private async updateFileWithParsed(
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		parsed: ParsedWorkout
	): Promise<void> {
		const newContent = serializeWorkout(parsed);
		const expectedTitle = parsed.metadata.title;
		// Update the code block with new content, title validation prevents cross-contamination
		await this.fileUpdater?.updateCodeBlock(ctx.sourcePath, sectionInfo, newContent, expectedTitle);
		
		// Optionally save metadata to Obsidian file properties (front matter)
		if (parsed.metadata.saveToProperties) {
			await this.fileUpdater?.saveToProperties(ctx.sourcePath, parsed);
		}
	}

	// ==================== CALLBACK HANDLERS ====================
	// These methods handle major workout flow events (start, finish, exercise transitions).
	// Each one updates the parsed state and persists changes to the file.

	/**
	 * Handles workout start: sets metadata, activates first exercise, starts timers.
	 * Flow: Set state → Find first exercise → Activate it → Save → Start timers
	 */
	private async handleStartWorkout(
		currentParsed: ParsedWorkout,
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string
	): Promise<void> {
		// Mark workout as started and record start time
		currentParsed.metadata.state = 'started';
		currentParsed.metadata.startDate = this.formatStartDate(new Date());

		// Find and activate the first pending exercise
		const firstPending = currentParsed.exercises.findIndex(e => e.state === 'pending');
		if (firstPending >= 0) {
			const exercise = currentParsed.exercises[firstPending];
			if (exercise) {
				exercise.state = 'inProgress';
			}
		}

		// Persist to file (state change must happen before timer starts)
		await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);

		// Start the workout timer at the first exercise
		this.timerManager.startWorkoutTimer(workoutId, firstPending >= 0 ? firstPending : 0);
	}

	/**
	 * Handles workout completion: calculates total time, locks fields, saves state.
	 * Flow: Get elapsed time → Mark completed → Lock all params → Save → Stop timers
	 */
	private async handleFinishWorkout(
		currentParsed: ParsedWorkout,
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string
	): Promise<void> {
		// Fetch total elapsed time from timer
		const timerState = this.timerManager.getTimerState(workoutId);
		if (timerState) {
			currentParsed.metadata.duration = formatDurationHuman(timerState.workoutElapsed);
		}

		// Mark workout as completed
		currentParsed.metadata.state = 'completed';

		// Lock all fields to prevent further edits once workout is done
		currentParsed = lockAllFields(currentParsed);

		// Persist final state to file
		await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);

		// Stop the workout timer in the timer manager
		this.timerManager.stopWorkoutTimer(workoutId);
	}

	/**
	 * Handles set completion: records duration, handles rest periods, advances to next set or exercise.
	 * This is the most complex flow with multiple branching scenarios:
	 *   - If more sets exist in exercise: Check for rest period, start rest or advance to next set
	 *   - If last set in exercise: Mark exercise done, find next exercise or complete workout
	 * 
	 * @returns Updated ParsedWorkout for callback closure to capture
	 */
	private async handleSetFinish(
		exerciseIndex: number,
		setIndex: number,
		currentParsed: ParsedWorkout,
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string,
		handleRestStart: (exerciseIndex: number, restDuration: number) => Promise<void>
	): Promise<ParsedWorkout> {
		const exercise = currentParsed.exercises[exerciseIndex];
		if (!exercise) return currentParsed;

		const timerState = this.timerManager.getTimerState(workoutId);

		// Step 1: Record how long this set actually took (from timer)
		if (timerState) {
			currentParsed = setSetRecordedDuration(
				currentParsed,
				exerciseIndex,
				setIndex,
				formatDurationHuman(timerState.exerciseElapsed)
			);
		}

		// Step 2: Mark current set as completed
		currentParsed = updateSetState(currentParsed, exerciseIndex, setIndex, 'completed');

		// Step 3: Check if current set has a rest period - logic is identical for both last and non-last sets
		const set = exercise.sets[setIndex];
		if (!set) return currentParsed;
		const restParam = set.params.find(p => p.key.toLowerCase() === 'rest');

		if (restParam) {
			// Has rest period - save state first, then start rest timer
			// This path applies whether it's the last set or not - handleRestEnd handles the logic after rest
			await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
			const restDurationSeconds = parseDurationToSeconds(restParam.value);
			await handleRestStart(exerciseIndex, restDurationSeconds);
		} else if (setIndex < exercise.sets.length - 1) {
			// No rest AND more sets exist - advance immediately to next set
			const nextSetIndex = setIndex + 1;
			currentParsed = updateSetState(currentParsed, exerciseIndex, nextSetIndex, 'inProgress');
			this.timerManager.advanceSet(workoutId, exerciseIndex, nextSetIndex);
			await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
		} else {
			// No rest AND last set - mark exercise as completed and look for next exercise
			currentParsed = updateExerciseState(currentParsed, exerciseIndex, 'completed');

			const nextPending = this.findNextPendingExercise(exerciseIndex, currentParsed.exercises);

			if (nextPending >= 0) {
				// Found next exercise - activate it
				currentParsed = updateExerciseState(currentParsed, nextPending, 'inProgress');
				this.timerManager.advanceExercise(workoutId, nextPending);
				await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
			} else {
				// No more exercises - complete the entire workout
				await this.completeWorkout(currentParsed, ctx, sectionInfo, workoutId);
			}
		}

		return currentParsed;
	}

	/**
	 * Handles rest period initiation: starts the rest timer in the timer manager.
	 * Called after a set is completed if a rest period is defined.
	 */
	private async handleRestStart(
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string,
		exerciseIndex: number,
		restDuration: number
	): Promise<void> {
		// Start counting down the rest period
		this.timerManager.startRest(workoutId, restDuration);
	}

	/**
	 * Handles rest period completion: advances to next set or exercise.
	 * Called when user finishes rest between sets. Similar branching to handleSetFinish.
	 */
	private async handleRestEnd(
		exerciseIndex: number,
		currentParsed: ParsedWorkout,
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string
	): Promise<ParsedWorkout> {
		const exercise = currentParsed.exercises[exerciseIndex];
		if (!exercise) return currentParsed;

		const activeSetIndex = this.timerManager.getActiveSetIndex(workoutId);

		// Record actual rest elapsed time before advancing
		const timerState = this.timerManager.getTimerState(workoutId);
		if (timerState && timerState.restElapsed !== undefined) {
			currentParsed = setSetRecordedRest(
				currentParsed,
				exerciseIndex,
				activeSetIndex,
				formatDurationHuman(timerState.restElapsed)
			);
		}

		// Rest finished, advance to next set
		const nextSetIndex = activeSetIndex + 1;
		if (nextSetIndex < exercise.sets.length) {
			// More sets exist - activate next one
			currentParsed = updateSetState(currentParsed, exerciseIndex, nextSetIndex, 'inProgress');
			this.timerManager.exitRest(workoutId, exerciseIndex, nextSetIndex);
			await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
		} else {
			// Last set done - move to next exercise
			currentParsed = updateExerciseState(currentParsed, exerciseIndex, 'completed');

			const nextPending = this.findNextPendingExercise(exerciseIndex, currentParsed.exercises);

			if (nextPending >= 0) {
				// Found next exercise
				currentParsed = updateExerciseState(currentParsed, nextPending, 'inProgress');
				this.timerManager.advanceExercise(workoutId, nextPending);
				await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
			} else {
				// No more exercises - complete entire workout
				await this.completeWorkout(currentParsed, ctx, sectionInfo, workoutId);
			}
		}

		return currentParsed;
	}

	/**
	 * Shared helper for marking workout as complete.
	 * Used when all exercises are done (called from multiple paths).
	 */
	private async completeWorkout(
		currentParsed: ParsedWorkout,
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string
	): Promise<void> {
		// Mark as completed and record final duration
		currentParsed.metadata.state = 'completed';
		const finalState = this.timerManager.getTimerState(workoutId);
		if (finalState) {
			currentParsed.metadata.duration = formatDurationHuman(finalState.workoutElapsed);
		}
		// Lock all fields to prevent editing after completion
		currentParsed = lockAllFields(currentParsed);
		// Persist and stop timers
		await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
		this.timerManager.stopWorkoutTimer(workoutId);
	}

	/**
	 * Handles user skipping current set: marks as skipped, advances to next set or exercise.
	 */
	private async handleExerciseSkip(
		exerciseIndex: number,
		currentParsed: ParsedWorkout,
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		workoutId: string
	): Promise<ParsedWorkout> {
		const exercise = currentParsed.exercises[exerciseIndex];
		if (!exercise) return currentParsed;

		const activeSetIndex = this.timerManager.getActiveSetIndex(workoutId);

		// Mark current set as skipped (user wants to skip, not complete)
		currentParsed = updateSetState(currentParsed, exerciseIndex, activeSetIndex, 'skipped');

		// Check if there are more sets in this exercise
		if (activeSetIndex < exercise.sets.length - 1) {
			// More sets exist - advance to next
			const nextSetIndex = activeSetIndex + 1;
			currentParsed = updateSetState(currentParsed, exerciseIndex, nextSetIndex, 'inProgress');
			this.timerManager.advanceSet(workoutId, exerciseIndex, nextSetIndex);
			await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
		} else {
			// Last set skipped - move to next exercise
			currentParsed = updateExerciseState(currentParsed, exerciseIndex, 'completed');

			const nextPending = this.findNextPendingExercise(exerciseIndex, currentParsed.exercises);

			if (nextPending >= 0) {
				currentParsed = updateExerciseState(currentParsed, nextPending, 'inProgress');

				// Advance timer BEFORE file update so re-render sees reset timer
				this.timerManager.advanceExercise(workoutId, nextPending);

				await this.updateFileWithParsed(ctx, sectionInfo, currentParsed);
			} else {
				// No more exercises, complete workout
				await this.completeWorkout(currentParsed, ctx, sectionInfo, workoutId);
			}
		}

		return currentParsed;
	}

	// ==================== CALLBACK CREATION ====================
	/**
	 * Creates the callback functions that are passed to the renderer.
	 * These callbacks handle all user interactions (buttons, input changes, etc).
	 * 
	 * The callbacks use a closure pattern to stay aware of:
	 * - currentParsed: Current state (updated as user interacts)
	 * - hasPendingChanges: Flag for debouncing param changes
	 * 
	 * Key patterns:
	 * - Workflow handlers (start, finish) call methods above
	 * - Param changes are batched and only flushed when leaving the field
	 * - All state changes flow through updateFile() to ensure persistence
	 */
	private createCallbacks(
		ctx: MarkdownPostProcessorContext,
		sectionInfo: SectionInfo | null,
		parsed: ParsedWorkout,
		workoutId: string
	): WorkoutCallbacks {
		// Closure variable: tracks the latest workout state as user interacts
		// Updated by updateFile() after each state change is persisted
		// Accessible to all callbacks so they see consistent state
		let currentParsed = parsed;
		
		// Closure variable: flag for debouncing parameter changes
		// When user edits a param in the UI:
		// 1. onParamChange sets hasPendingChanges = true (but doesn't save)
		// 2. When user leaves the field, onFlushChanges is called
		// 3. flushChanges() checks flag and only saves if true
		// This reduces write frequency when user is rapidly typing
		let hasPendingChanges = false;

		// Helper: Persists state to file and updates closure variables
		// All major workflow changes (start, finish, exercise transitions) call this
		// Ensures file is always in sync with timer state
		const updateFile = async (newParsed: ParsedWorkout): Promise<void> => {
			// Update closure state to latest value
			currentParsed = newParsed;
			// Clear pending changes flag since we just flushed
			hasPendingChanges = false;
			// Serialize to markdown and write to file (also saves to properties if enabled)
			await this.updateFileWithParsed(ctx, sectionInfo, newParsed);
		};

		// Helper: Saves pending parameter changes to file if any exist
		// Called when user leaves a parameter field (onBlur event)
		// If hasPendingChanges is true, calls updateFile to persist
		// If false, does nothing (optimization - skip unnecessary writes)
		const flushChanges = async (): Promise<void> => {
			if (hasPendingChanges) {
				// User made changes - persist them
				await updateFile(currentParsed);
			}
			// If no pending changes, onFlushChanges is essentially a no-op
		};

		return {
			// ===== WORKFLOW HANDLERS (Major state transitions) =====
			
			// User clicked "Start Workout" button
			// Sets state to 'started', activates first exercise, starts timers
			onStartWorkout: async (): Promise<void> => {
				await this.handleStartWorkout(currentParsed, ctx, sectionInfo, workoutId);
			},

			// User clicked "Finish Workout" button or all exercises completed
			// Captures total elapsed time, locks all fields, marks as 'completed'
			onFinishWorkout: async (): Promise<void> => {
				await this.handleFinishWorkout(currentParsed, ctx, sectionInfo, workoutId);
			},

			// Timer completed (either countdown finished or user clicked "Done")
			// Routes to either handleRestEnd (if in rest period) or handleSetFinish (if in set)
			// Determines what comes next: rest, next set, next exercise, or complete
			onExerciseFinish: async (exerciseIndex: number): Promise<void> => {
				// Check timer state to see if we're in rest period or active exercise
				const activeSetIndex = this.timerManager.getActiveSetIndex(workoutId);
				const timerState = this.timerManager.getTimerState(workoutId);
				
				// Route to appropriate handler based on whether rest is active
				if (timerState?.isRestActive) {
					// In rest period - advance to next set after rest
					currentParsed = await this.handleRestEnd(exerciseIndex, currentParsed, ctx, sectionInfo, workoutId);
				} else {
					// In active set/exercise - finish set and check for rest or next
					currentParsed = await this.handleSetFinish(
						exerciseIndex,
						activeSetIndex,
						currentParsed,
						ctx,
						sectionInfo,
						workoutId,
						this.handleRestStart.bind(this, ctx, sectionInfo, workoutId)
					);
				}
			},

			// Explicit set finish (alternative to onExerciseFinish when only marking a set complete)
			// Called from UI when user clicks "Done" on a specific set
			onSetFinish: async (exerciseIndex: number, setIndex: number): Promise<void> => {
				currentParsed = await this.handleSetFinish(
					exerciseIndex,
					setIndex,
					// Pass closure state and update it with returned value
					currentParsed,
					ctx,
					sectionInfo,
					workoutId,
					// Callback for rest handling if this set has rest duration
					async (exIdx: number, restDur: number) => {
						await this.handleRestStart(ctx, sectionInfo, workoutId, exIdx, restDur);
					}
				);
			},

			// Rest period is starting (e.g., user clicked "Start Rest" or after auto-rest)
			// Initializes countdown timer for the rest period
			onRestStart: async (exerciseIndex: number, restDuration: number): Promise<void> => {
				await this.handleRestStart(ctx, sectionInfo, workoutId, exerciseIndex, restDuration);
			},

			// Rest period is ending (countdown finished or user clicked "Skip Rest")
			// Advances to next set after recording rest duration
			onRestEnd: async (exerciseIndex: number): Promise<void> => {
				currentParsed = await this.handleRestEnd(exerciseIndex, currentParsed, ctx, sectionInfo, workoutId);
			},

			// ===== USER ACTIONS (In-flight modifications) =====
			
			// User clicked "Add Set" button during exercise
			// Clones the current set as template, records current time, advances timer
			// Allows user to do more reps/sets than originally planned
			onExerciseAddSet: async (exerciseIndex: number): Promise<void> => {
				// User wants to add a set to current exercise while working out
				// This records the current set duration before creating a new one
				const exercise = currentParsed.exercises[exerciseIndex];
				if (!exercise) return;

				const activeSetIndex = this.timerManager.getActiveSetIndex(workoutId);
				const timerState = this.timerManager.getTimerState(workoutId);
				if (timerState) {
					currentParsed = setSetRecordedDuration(
						currentParsed,
						exerciseIndex,
						activeSetIndex,
						formatDurationHuman(timerState.exerciseElapsed)
					);
				}

				// Mark current set done and activate the new set
				currentParsed = updateSetState(currentParsed, exerciseIndex, activeSetIndex, 'completed');
				currentParsed = addSet(currentParsed, exerciseIndex);

				const newSetIndex = (currentParsed.exercises[exerciseIndex]?.sets.length ?? 1) - 1;
				currentParsed = updateSetState(currentParsed, exerciseIndex, newSetIndex, 'inProgress');

				// Update timer to track new set
				this.timerManager.advanceSet(workoutId, exerciseIndex, newSetIndex);
				await updateFile(currentParsed);
			},

			// User clicked "Add Rest" button to insert unplanned rest
			// Creates a Rest exercise at the next position and starts countdown
			onExerciseAddRest: async (exerciseIndex: number): Promise<void> => {
				// User wants to insert a rest period (creates a new rest exercise after current one)
				const exercise = currentParsed.exercises[exerciseIndex];
				const restDuration = currentParsed.metadata.restDuration;
				if (!exercise || !restDuration) return;

				const activeSetIndex = this.timerManager.getActiveSetIndex(workoutId);
				const timerState = this.timerManager.getTimerState(workoutId);
				
				// Record how long the current set took before rest
				if (timerState) {
					currentParsed = setSetRecordedDuration(
						currentParsed,
						exerciseIndex,
						activeSetIndex,
						formatDurationHuman(timerState.exerciseElapsed)
					);
				}

				// Mark current set done, insert new Rest exercise after current one
				currentParsed = updateSetState(currentParsed, exerciseIndex, activeSetIndex, 'completed');
				currentParsed = addRest(currentParsed, exerciseIndex, restDuration);
				// Activate the rest exercise (this is at index exerciseIndex+1)
				currentParsed = updateExerciseState(currentParsed, exerciseIndex + 1, 'inProgress');

				// Update timer to track new rest exercise
				this.timerManager.advanceSet(workoutId, exerciseIndex + 1, 0);
				await updateFile(currentParsed);
			},

			// User clicked "Skip" button to skip current set without completing it
			// Marks as 'skipped' (not 'completed'), advances to next set or exercise
			onExerciseSkip: async (exerciseIndex: number): Promise<void> => {
				// User wants to skip current set/exercise
				currentParsed = await this.handleExerciseSkip(exerciseIndex, currentParsed, ctx, sectionInfo, workoutId);
			},

			// ===== PARAMETER EDITING (Debounced changes) =====
			
			// User is editing an exercise-level param (e.g., weight field, notes)
			// Debounced: doesn't save immediately, only sets flag for later flush
			// This prevents excessive file writes while user is typing
			onParamChange: (exerciseIndex: number, paramKey: string, newValue: string): void => {
				// User edited an exercise param (e.g., weight, reps)
				// Mark as pending change (debounced - won't save until blur/flush)
				const exercise = currentParsed.exercises[exerciseIndex];
				const param = exercise?.params.find(p => p.key === paramKey);
				if (param?.value === newValue) return; // No change, skip
				currentParsed = updateParamValue(currentParsed, exerciseIndex, paramKey, newValue);
				hasPendingChanges = true; // Flag for later flush
			},

			// User is editing a set-level param (e.g., reps field, weight field)
			// Debounced: doesn't save immediately, only sets flag for later flush
			onSetParamChange: (exerciseIndex: number, setIndex: number, paramKey: string, newValue: string): void => {
				// User edited a set param (e.g., duration, weight, reps)
				// Mark as pending change (debounced - won't save until blur/flush)
				const exercise = currentParsed.exercises[exerciseIndex];
				const set = exercise?.sets[setIndex];
				const param = set?.params.find(p => p.key === paramKey);
				if (param?.value === newValue) return; // No change, skip
				currentParsed = updateSetParamValue(currentParsed, exerciseIndex, setIndex, paramKey, newValue);
				hasPendingChanges = true; // Flag for later flush
			},

			// User left a parameter field (blur event) - flush any pending changes
			// Called after onParamChange/onSetParamChange to persist edited params
			// Implementation is the flushChanges helper defined above
			onFlushChanges: flushChanges,

			// ===== TIMER CONTROLS (Pause/Resume) =====
			
			// User clicked "Pause" button - temporarily stops timer without finishing
			// Exercise remains "in-progress", elapsed time recorded at pause point
			onPauseExercise: (): void => {
				// User paused the timer (stops counting but doesn't finish/advance)
				this.timerManager.pauseExercise(workoutId);
			},

			// User clicked "Resume" after pausing - continues timer from pause point
			// Resumes from the same elapsed time, not restarting
			onResumeExercise: (): void => {
				// User resumed the paused timer to continue counting
				this.timerManager.resumeExercise(workoutId);
			},

			// ===== SPECIAL ACTIONS =====
			
			// User clicked "Load Sample Workout" button to populate empty workout
			// Generates a demo workout with various exercise types for exploration
			onAddSample: async (): Promise<void> => {
				// User clicked "Load Sample" - creates a demo workout to explore features
				const sampleWorkout = createSampleWorkout();
				const newContent = serializeWorkout(sampleWorkout);
				// Replace current workout with sample
				await this.fileUpdater?.updateCodeBlock(
					ctx.sourcePath,
					sectionInfo,
					newContent,
					sampleWorkout.metadata.title
				);
			}
		};
	}

	/**
	 * Formats a date into workout metadata format: YYYY-MM-DD HH:MM
	 * Used for recording workout start time.
	 */
	private formatStartDate(date: Date): string {
		const year = date.getFullYear();
		const month = String(date.getMonth() + 1).padStart(2, '0');
		const day = String(date.getDate()).padStart(2, '0');
		const hours = String(date.getHours()).padStart(2, '0');
		const minutes = String(date.getMinutes()).padStart(2, '0');
		return `${year}-${month}-${day} ${hours}:${minutes}`;
	}
}
